language: c
env:
  - nim_branch=master
  - nim_branch=devel
matrix:
  allow_failures:
    - env: nim_branch=devel
  fast_finish: true
install:
  - |
    if [ ! -x nim-$nim_branch/bin/nim ]; then
      git clone -b $nim_branch --depth 1 git://github.com/nim-lang/nim nim-$nim_branch/
      cd nim-$nim_branch
      git clone --depth 1 git://github.com/nim-lang/csources csources/
      cd csources
      sh build.sh
      cd ..
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
      ./koch nimble
    else
      cd nim-$nim_branch
      git fetch origin
      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
        bin/nim c koch
        ./koch boot -d:release
        ./koch nimble
      fi
    fi
    cd ..
before_script:
  - export PATH="nim-$nim_branch/bin${PATH:+:$PATH}"
  - export NIM_LIB_PREFIX="$(pwd)/nim-$nim_branch"
script:
  - nim c -d:release nimspire.nim
cache:
  directories:
    - nim-master
    - nim-devel
dist: bionic
